# Generated by Django 5.2.7 on 2025-11-02 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_city_city_name_en_city_city_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='booking_app.hotel'),
        ),
    ]
